import { Mentor, Group, Project } from '@/app/types';

export const mockMentor: Mentor = {
  id: '1',
  firstName: 'Алексей',
  lastName: 'Иванов',
  middleName: 'Петрович',
  photo: 'https://images.unsplash.com/photo-1758685845906-6f705cde4fb7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBtZW50b3IlMjB0ZWFjaGVyfGVufDF8fHx8MTc2ODc1MDU3NXww&ixlib=rb-4.1.0&q=80&w=1080',
  bio: 'Ментор с 5-летним опытом преподавания программирования детям. Специализируюсь на Python, JavaScript и визуальном программировании. Помогаю студентам создавать их первые проекты и развивать навыки алгоритмического мышления.',
};

export const mockGroups: Group[] = [
  {
    id: 'g1',
    name: 'Scratch Начинающие',
    category: 'Scratch',
    students: [
      { id: 's1', firstName: 'Даниил', lastName: 'Смирнов' },
      { id: 's2', firstName: 'София', lastName: 'Козлова' },
      { id: 's3', firstName: 'Артём', lastName: 'Новиков' },
      { id: 's4', firstName: 'Мария', lastName: 'Соколова' },
      { id: 's5', firstName: 'Максим', lastName: 'Лебедев' },
      { id: 's6', firstName: 'Анна', lastName: 'Егорова' },
      { id: 's7', firstName: 'Иван', lastName: 'Павлов' },
      { id: 's8', firstName: 'Елизавета', lastName: 'Морозова' },
      { id: 's9', firstName: 'Дмитрий', lastName: 'Петров' },
      { id: 's10', firstName: 'Виктория', lastName: 'Волкова' },
    ],
  },
  {
    id: 'g2',
    name: 'Python Продвинутые',
    category: 'Python',
    students: [
      { id: 's11', firstName: 'Александр', lastName: 'Васильев' },
      { id: 's12', firstName: 'Екатерина', lastName: 'Соловьева' },
      { id: 's13', firstName: 'Михаил', lastName: 'Зайцев' },
      { id: 's14', firstName: 'Полина', lastName: 'Романова' },
      { id: 's15', firstName: 'Кирилл', lastName: 'Федоров' },
      { id: 's16', firstName: 'Дарья', lastName: 'Николаева' },
      { id: 's17', firstName: 'Егор', lastName: 'Семенов' },
      { id: 's18', firstName: 'Алина', lastName: 'Голубева' },
      { id: 's19', firstName: 'Никита', lastName: 'Виноградов' },
      { id: 's20', firstName: 'Олеся', lastName: 'Кузнецова' },
      { id: 's21', firstName: 'Тимофей', lastName: 'Орлов' },
      { id: 's22', firstName: 'Милана', lastName: 'Андреева' },
    ],
  },
  {
    id: 'g3',
    name: 'Web-разработка',
    category: 'HTML/CSS',
    students: [
      { id: 's23', firstName: 'Артур', lastName: 'Макаров' },
      { id: 's24', firstName: 'Ксения', lastName: 'Ильина' },
      { id: 's25', firstName: 'Глеб', lastName: 'Степанов' },
      { id: 's26', firstName: 'Арина', lastName: 'Борисова' },
      { id: 's27', firstName: 'Роман', lastName: 'Захаров' },
      { id: 's28', firstName: 'Валерия', lastName: 'Крылова' },
      { id: 's29', firstName: 'Владислав', lastName: 'Григорьев' },
      { id: 's30', firstName: 'Ульяна', lastName: 'Денисова' },
      { id: 's31', firstName: 'Матвей', lastName: 'Медведев' },
      { id: 's32', firstName: 'Вероника', lastName: 'Белова' },
      { id: 's33', firstName: 'Андрей', lastName: 'Тарасов' },
    ],
  },
  {
    id: 'g4',
    name: 'React Разработчики',
    category: 'JS(React)',
    students: [
      { id: 's34', firstName: 'Павел', lastName: 'Яковлев' },
      { id: 's35', firstName: 'Диана', lastName: 'Комарова' },
      { id: 's36', firstName: 'Сергей', lastName: 'Антонов' },
      { id: 's37', firstName: 'Кристина', lastName: 'Тихонова' },
      { id: 's38', firstName: 'Илья', lastName: 'Филиппов' },
      { id: 's39', firstName: 'Маргарита', lastName: 'Сергеева' },
      { id: 's40', firstName: 'Богдан', lastName: 'Давыдов' },
      { id: 's41', firstName: 'Евгения', lastName: 'Волкова' },
      { id: 's42', firstName: 'Юрий', lastName: 'Кириллов' },
      { id: 's43', firstName: 'Татьяна', lastName: 'Максимова' },
    ],
  },
  {
    id: 'g5',
    name: 'Roblox Creators',
    category: 'Roblox',
    students: [
      { id: 's44', firstName: 'Денис', lastName: 'Алексеев' },
      { id: 's45', firstName: 'Мирослава', lastName: 'Савельева' },
      { id: 's46', firstName: 'Константин', lastName: 'Никитин' },
      { id: 's47', firstName: 'Лилия', lastName: 'Захарова' },
      { id: 's48', firstName: 'Николай', lastName: 'Королев' },
      { id: 's49', firstName: 'Камила', lastName: 'Михайлова' },
      { id: 's50', firstName: 'Федор', lastName: 'Климов' },
      { id: 's51', firstName: 'Елена', lastName: 'Федорова' },
      { id: 's52', firstName: 'Станислав', lastName: 'Воробьев' },
      { id: 's53', firstName: 'Ангелина', lastName: 'Попова' },
      { id: 's54', firstName: 'Георгий', lastName: 'Ковалев' },
      { id: 's55', firstName: 'Виолетта', lastName: 'Белякова' },
      { id: 's56', firstName: 'Владимир', lastName: 'Соболев' },
      { id: 's57', firstName: 'Алиса', lastName: 'Мартынова' },
      { id: 's58', firstName: 'Ярослав', lastName: 'Фролов' },
    ],
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    name: 'Космическое приключение',
    description: 'Интерактивная игра в Scratch про космонавта, исследующего новые планеты. Игрок собирает звезды и избегает препятствий.',
    type: 'individual',
    studentIds: ['s1'],
    groupId: 'g1',
    category: 'Scratch',
    files: [
      { name: 'space_adventure.sb3', type: 'zip', url: '#', size: '2.4 MB' },
      { name: 'presentation.pdf', type: 'presentation', url: '#', size: '1.8 MB' },
      { name: 'screenshot1.png', type: 'image', url: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=800', size: '0.5 MB' },
    ],
    createdAt: '2026-01-10',
  },
  {
    id: 'p2',
    name: 'Математический квест',
    description: 'Командный проект: образовательная игра для изучения таблицы умножения с яркими персонажами и уровнями сложности.',
    type: 'team',
    studentIds: ['s2', 's3', 's4'],
    groupId: 'g1',
    category: 'Scratch',
    files: [
      { name: 'math_quest.sb3', type: 'zip', url: '#', size: '3.1 MB' },
      { name: 'team_presentation.pdf', type: 'presentation', url: '#', size: '2.2 MB' },
      { name: 'game_screen1.png', type: 'image', url: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800', size: '0.6 MB' },
      { name: 'game_screen2.png', type: 'image', url: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=800', size: '0.7 MB' },
    ],
    createdAt: '2026-01-12',
  },
  {
    id: 'p3',
    name: 'Анализатор текста',
    description: 'Python приложение для анализа текстовых файлов: подсчет слов, частота букв, самые используемые слова. С графическим интерфейсом на Tkinter.',
    type: 'individual',
    studentIds: ['s11'],
    groupId: 'g2',
    category: 'Python',
    files: [
      { name: 'text_analyzer.zip', type: 'zip', url: '#', size: '1.2 MB' },
      { name: 'demo.pdf', type: 'presentation', url: '#', size: '1.5 MB' },
      { name: 'ui_screenshot.png', type: 'image', url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800', size: '0.4 MB' },
    ],
    createdAt: '2026-01-08',
  },
  {
    id: 'p4',
    name: 'Погодное приложение',
    description: 'Приложение на Python с использованием API для получения данных о погоде. Визуализация данных с помощью matplotlib.',
    type: 'team',
    studentIds: ['s12', 's13'],
    groupId: 'g2',
    category: 'Python',
    files: [
      { name: 'weather_app.zip', type: 'zip', url: '#', size: '2.8 MB' },
      { name: 'presentation.pdf', type: 'presentation', url: '#', size: '2.1 MB' },
      { name: 'chart1.png', type: 'image', url: 'https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=800', size: '0.5 MB' },
      { name: 'chart2.png', type: 'image', url: 'https://images.unsplash.com/photo-1561553873-e8491a564fd0?w=800', size: '0.6 MB' },
    ],
    createdAt: '2026-01-14',
  },
  {
    id: 'p5',
    name: 'Портфолио сайт',
    description: 'Личный веб-сайт портф��лио с адаптивным дизайном, использующий HTML5, CSS3 и анимации.',
    type: 'individual',
    studentIds: ['s23'],
    groupId: 'g3',
    category: 'HTML/CSS',
    files: [
      { name: 'portfolio_site.zip', type: 'zip', url: '#', size: '5.3 MB' },
      { name: 'showcase.pdf', type: 'presentation', url: '#', size: '3.2 MB' },
      { name: 'homepage.png', type: 'image', url: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800', size: '0.8 MB' },
    ],
    createdAt: '2026-01-11',
  },
  {
    id: 'p6',
    name: 'Интернет-магазин товаров',
    description: 'Веб-приложение на React с каталогом товаров, корзиной покупок, фильтрацией и поиском. Использует React Hooks и Context API.',
    type: 'team',
    studentIds: ['s34', 's35', 's36'],
    groupId: 'g4',
    category: 'JS(React)',
    files: [
      { name: 'shop_app.zip', type: 'zip', url: '#', size: '8.7 MB' },
      { name: 'project_demo.pdf', type: 'presentation', url: '#', size: '4.1 MB' },
      { name: 'catalog.png', type: 'image', url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800', size: '1.1 MB' },
      { name: 'cart.png', type: 'image', url: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800', size: '0.9 MB' },
    ],
    createdAt: '2026-01-15',
  },
  {
    id: 'p7',
    name: 'Обби парк приключений',
    description: 'Игра в Roblox с препятствиями разной сложности, системой чекпоинтов и лидербордом. Включает 15 уникальных уровней.',
    type: 'team',
    studentIds: ['s44', 's45', 's46', 's47'],
    groupId: 'g5',
    category: 'Roblox',
    files: [
      { name: 'obby_park.rbxl', type: 'zip', url: '#', size: '12.4 MB' },
      { name: 'game_design.pdf', type: 'presentation', url: '#', size: '5.6 MB' },
      { name: 'level1.png', type: 'image', url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800', size: '1.3 MB' },
      { name: 'level2.png', type: 'image', url: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=800', size: '1.2 MB' },
      { name: 'leaderboard.png', type: 'image', url: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800', size: '0.7 MB' },
    ],
    createdAt: '2026-01-13',
  },
  {
    id: 'p8',
    name: 'Todo приложение',
    description: 'React приложение для управления задачами с возможностью добавления, редактирования, удаления и фильтрации задач. Responsive дизайн.',
    type: 'individual',
    studentIds: ['s37'],
    groupId: 'g4',
    category: 'JS(React)',
    files: [
      { name: 'todo_app.zip', type: 'zip', url: '#', size: '3.9 MB' },
      { name: 'presentation.pdf', type: 'presentation', url: '#', size: '1.7 MB' },
      { name: 'app_view.png', type: 'image', url: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800', size: '0.6 MB' },
    ],
    createdAt: '2026-01-16',
  },
];
